---
- hosts: all

  vars:
    rbenv_versions:
      - 2.2.4
    applications:
      - alfred
      - atom
      - caffeine
      - chromium
      - clipmenu
      - docker
      - firefox
      - flux
      - google-chrome
      - google-drive
      - hipchat
      - intellij-idea
      - iterm2
      - kindle
      - macvim
      - mou
      - postgres
      - postman
      - robomongo
      - rubymine
      - slack
      - sublime-text
      - the-unarchiver
      - virtualbox
      - vlc
    other_apps:
      - intellij-idea-ce
    application_dir: /Applications
    brews:
      - ack
      - ansible
      - ant
      - argtable
      - autoconf
      - boost
      - cmake
      - cowsay
      - cryptopp
      - ctags
      - curl
      - d-bus
      - docker
      - docker-machine
      - eris
      - fortune
      - freetype
      - gdbm
      - gettext
      - glib
      - gmp
      - gnutls
      - go
      #- gradle
      - imagemagick
      #- instantclient-basic
      #- instantclient-sdk
      - ios-sim
      - irssi
      - jpeg
      - jsoncpp
      - leiningen
      - leveldb
      - libevent
      - libffi
      - libjson-rpc-cpp
      - libmemcached
      - libmicrohttpd
      - libpng
      - libtasn1
      - libtiff
      - libtool
      - libyaml
      #- llvm37
      - lua
      #- luarocks
      #- maven
      - memcached
      - mercurial
      - mergepbx
      - miniupnpc
      - mongodb
      - mysql
      - ncftp
      - nettle
      - nmap
      - node
      - openssl
      - packer
      - pcre
      - phantomjs
      - pixman
      - pkg-config
      - python
      - python3
      - qemu
      - qt5
      - rbenv
      - readline
      - reattach-to-user-namespace
      - ruby-build
      #- scala
      - sdl
      - snappy
      - sqlite
      - terraform
      - the_silver_searcher
      - tig
      - tmux
      #- tomcat
      - tree
      - vault
      - wget
      - xz
    dotfiles_dir: /Users/derekgliwa/dotfiles
    email: dgliwa@thoughtworks.com
    github_username: dgliwa
    home_dir: /Users/derekgliwa
    name: Derek Gliwa
    zsh_path: /bin/zsh

  tasks:
    - include: tasks/homebrew.yml
      tags: [homebrew]
    - include: tasks/zsh.yml
      tags: [zsh]
    - include: tasks/dotfiles.yml
      tags: [dotfiles]
    - include: tasks/rbenv.yml
      tags: [rbenv]
