---
- hosts: all

  vars:
    brews:
      - git
      - neovim
      - ripgrep
      - tree-sitter
      - uv
      - vcprompt
    casks:
      - alfred
      - arc
      - discord
      - obsidian
      - postico
      - rectangle
      - spotify
      - visual-studio-code
      - wezterm

  tasks:
    - name: Install brews
      ansible.builtin.include_tasks:
        file: tasks/homebrew.yml
        apply:
          tags: [brew]
    - name: Configure git
      ansible.builtin.include_tasks:
        file: tasks/git.yml
        apply:
          tags: [git]
    - name: Install asdf
      ansible.builtin.include_tasks:
        file: tasks/asdf.yml
        apply:
          tags: [asdf]
    - name: Configure nvim
      ansible.builtin.include_tasks:
        file: tasks/nvim.yml
        apply:
          tags: [nvim]
    - name: Configure omz
      ansible.builtin.include_tasks:
        file: tasks/omz.yml
        apply:
          tags: [omz]
    - name: Link shell configuration
      ansible.builtin.include_tasks:
        file: tasks/terminal.yml
        apply:
          tags: [terminal]
    - name: Link wezterm config
      ansible.builtin.include_tasks:
        file: tasks/wezterm.yml
        apply:
          tags: [wezterm]
    - name: Install docker
      ansible.builtin.include_tasks:
        file: tasks/docker.yml
        apply:
          tags: [docker]
