---
- name: Check rcm is installed
  stat: path=/usr/local/bin/rcup
  register: rcm_installed

- name: Install rcm for dotfiles management
  shell: brew tap thoughtbot/formulae && brew install rcm
  when: rcm_installed.stat.exists == false

- name: Check out dotfiles repo
  git:
    repo: git@github.com:dgliwa/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    accept_hostkey: yes

- name: Apply dotfiles
  shell: rcup -f -d {{ dotfiles_dir }}

- name: Install vim plugins
  shell: vim +PluginInstall +qall

- name: Apply local git config
  template: src=templates/gitconfig dest={{home_dir}}/.gitconfig
