- name: Install homebrew dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brews }}"

- name: Install cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ casks }}"

