- name: Check zshrc
  stat: path="{{ansible_env.HOME}}/.zshrc"
  register: zshrc
  
- name: Check colors
  stat: path="{{ansible_env.HOME}}/.colors"
  register: colors
  
- name: Check exports
  stat: path="{{ansible_env.HOME}}/.exports"
  register: exports
  
- name: Check aliases
  stat: path="{{ansible_env.HOME}}/.aliases"
  register: aliases
  
- name: Check gitignore
  stat: path="{{ansible_env.HOME}}/.gitignore"
  register: gitignore
  
- name: Check tmuxconfig
  stat: path="{{ansible_env.HOME}}/.tmux.conf"
  register: tmuxconfig

- name: Backup zshrc
  ansible.builtin.shell:
    cmd: "mv {{ansible_env.HOME}}/.zshrc {{ansible_env.HOME}}/.zshrc.bak"
  when: zshrc.stat.exists == True and (zshrc.stat.islnk == False or zshrc.stat.lnk_target != "{{playbook_dir}}/files/zshrc")
  
- name: Backup colors
  ansible.builtin.shell:
    cmd: "mv {{ansible_env.HOME}}/.colors {{ansible_env.HOME}}/.colors.bak"
  when: colors.stat.exists == True and (colors.stat.islnk == False or colors.stat.lnk_target != "{{playbook_dir}}/files/colors")
  
- name: Backup exports
  ansible.builtin.shell:
    cmd: "mv {{ansible_env.HOME}}/.exports {{ansible_env.HOME}}/.exports.bak"
  when: exports.stat.exists == True and (exports.stat.islnk == False or exports.stat.lnk_target != "{{playbook_dir}}/files/exports")
  
- name: Backup aliases
  ansible.builtin.shell:
    cmd: "mv {{ansible_env.HOME}}/.aliases {{ansible_env.HOME}}/.aliases.bak"
  when: aliases.stat.exists == True and (aliases.stat.islnk == False or aliases.stat.lnk_target != "{{playbook_dir}}/files/aliases")
  
- name: Backup gitignore
  ansible.builtin.shell:
    cmd: "mv {{ansible_env.HOME}}/.gitignore {{ansible_env.HOME}}/.gitignore.bak"
  when: gitignore.stat.exists == True and (gitignore.stat.islnk == False or gitignore.stat.lnk_target != "{{playbook_dir}}/files/gitignore")
  
- name: Backup tmuxconfig
  ansible.builtin.shell:
    cmd: "mv {{ansible_env.HOME}}/.tmux.conf {{ansible_env.HOME}}/.tmux.conf.bak"
  when: tmuxconfig.stat.exists == True and (tmuxconfig.stat.islnk == False or tmuxconfig.stat.lnk_target != "{{playbook_dir}}/files/tmux.config")
  
- name: Link to zshrc
  ansible.builtin.file:
    src: "{{playbook_dir}}/files/zshrc"
    dest: "{{ansible_env.HOME}}/.zshrc"
    state: link
    
- name: Link to colors
  ansible.builtin.file:
    src: "{{playbook_dir}}/files/colors"
    dest: "{{ansible_env.HOME}}/.colors"
    state: link
  
- name: link to exports
  ansible.builtin.file:
    src: "{{playbook_dir}}/files/exports"
    dest: "{{ansible_env.HOME}}/.exports"
    state: link

- name: Link to aliases
  ansible.builtin.file:
    src: "{{playbook_dir}}/files/aliases"
    dest: "{{ansible_env.HOME}}/.aliases"
    state: link
    
- name: Link to gitignore
  ansible.builtin.file:
    src: "{{playbook_dir}}/files/gitignore"
    dest: "{{ansible_env.HOME}}/.gitignore"
    state: link
    
- name: Link to tmuxconfig
  ansible.builtin.file:
    src: "{{playbook_dir}}/files/tmux.conf"
    dest: "{{ansible_env.HOME}}/.tmux.config"
    state: link
